# Site settings
title: Wesley Reunion
email: dp3athome@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "wesleyreunion.com" # the base hostname & protocol for your site

twitter_username:
github_username:
instagram_username: wesleyatkstate
facebook_username: kstatewesley

# Build settings
markdown: kramdown
